// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wafi.BusReservationSystem.Infrastructure.Data;

#nullable disable

namespace Wafi.BusReservationSystem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WafiDbContext))]
    [Migration("20251028124826_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Bus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BusType")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2b7e02c-0382-4f4f-9f88-eb2a6e0c27f8"),
                            BusType = 1,
                            CompanyName = "Green Line Paribahan",
                            Name = "Green Line Express",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = new Guid("aee2a129-1088-405d-9e02-7b78bae81ba1"),
                            BusType = 0,
                            CompanyName = "Hanif Paribahan",
                            Name = "Hanif Enterprise",
                            TotalSeats = 36
                        });
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.BusSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("BusId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("JourneyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("RouteId");

                    b.ToTable("BusSchedules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5b270af-9491-4b8d-953e-126aa36820b7"),
                            ArrivalTime = new TimeSpan(0, 12, 0, 0, 0),
                            BusId = new Guid("a2b7e02c-0382-4f4f-9f88-eb2a6e0c27f8"),
                            DepartureTime = new TimeSpan(0, 7, 0, 0, 0),
                            JourneyDate = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 800,
                            RouteId = new Guid("b3c689f4-4c78-4a7c-9023-3b91a15519a0")
                        },
                        new
                        {
                            Id = new Guid("8a21b9e8-baee-4a3e-ae0b-9ab1c812f268"),
                            ArrivalTime = new TimeSpan(0, 13, 30, 0, 0),
                            BusId = new Guid("aee2a129-1088-405d-9e02-7b78bae81ba1"),
                            DepartureTime = new TimeSpan(0, 8, 0, 0, 0),
                            JourneyDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 700,
                            RouteId = new Guid("d0be67e9-292e-4b0c-8c0d-1bb0a1e2e1a1")
                        });
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f91d9f76-694c-42d5-afca-69252dc86eff"),
                            Name = "Dhaka"
                        },
                        new
                        {
                            Id = new Guid("c85c3f39-ab09-43b1-9b5c-32d7e420f9a1"),
                            Name = "Rajshahi"
                        },
                        new
                        {
                            Id = new Guid("39b76299-f549-4fc6-99a0-a15a607cb510"),
                            Name = "Sirajgonj"
                        },
                        new
                        {
                            Id = new Guid("4db86802-9aea-4e7e-801a-b05a2463be39"),
                            Name = "Khulna"
                        });
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Passenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1aa236b-9611-4e2c-8157-64a4be53c3ad"),
                            MobileNumber = "01776913524",
                            Name = "Sabbir Ahmed"
                        },
                        new
                        {
                            Id = new Guid("d31771d2-0c5e-4e1f-92f0-4d68c6e3123f"),
                            MobileNumber = "01976913524",
                            Name = "Hasan Tarik"
                        });
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BoardingPointId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DroppingPointId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3c689f4-4c78-4a7c-9023-3b91a15519a0"),
                            BoardingPointId = new Guid("f91d9f76-694c-42d5-afca-69252dc86eff"),
                            DroppingPointId = new Guid("c85c3f39-ab09-43b1-9b5c-32d7e420f9a1"),
                            Name = "Dhaka to Rajshahi"
                        },
                        new
                        {
                            Id = new Guid("d0be67e9-292e-4b0c-8c0d-1bb0a1e2e1a1"),
                            BoardingPointId = new Guid("c85c3f39-ab09-43b1-9b5c-32d7e420f9a1"),
                            DroppingPointId = new Guid("f91d9f76-694c-42d5-afca-69252dc86eff"),
                            Name = "Rajshahi to Dhaka"
                        });
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.RouteDroppingPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("ArrivalTime")
                        .HasColumnType("interval");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("DepartureTime")
                        .HasColumnType("interval");

                    b.Property<int>("DroppingPointsOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteDroppingPoints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eab6b539-1981-460d-a0e1-7ee4a53b1299"),
                            ArrivalTime = new TimeSpan(0, 7, 0, 0, 0),
                            CityId = new Guid("f91d9f76-694c-42d5-afca-69252dc86eff"),
                            DepartureTime = new TimeSpan(0, 7, 15, 0, 0),
                            DroppingPointsOrder = 1,
                            RouteId = new Guid("b3c689f4-4c78-4a7c-9023-3b91a15519a0")
                        },
                        new
                        {
                            Id = new Guid("bf14e6d2-ba55-4fbb-ac59-48a5f8a6407a"),
                            ArrivalTime = new TimeSpan(0, 9, 30, 0, 0),
                            CityId = new Guid("39b76299-f549-4fc6-99a0-a15a607cb510"),
                            DepartureTime = new TimeSpan(0, 9, 45, 0, 0),
                            DroppingPointsOrder = 2,
                            RouteId = new Guid("b3c689f4-4c78-4a7c-9023-3b91a15519a0")
                        },
                        new
                        {
                            Id = new Guid("c318afac-ee1a-43ba-97f1-79acbd78d2a5"),
                            ArrivalTime = new TimeSpan(0, 12, 0, 0, 0),
                            CityId = new Guid("c85c3f39-ab09-43b1-9b5c-32d7e420f9a1"),
                            DepartureTime = new TimeSpan(0, 12, 15, 0, 0),
                            DroppingPointsOrder = 3,
                            RouteId = new Guid("b3c689f4-4c78-4a7c-9023-3b91a15519a0")
                        });
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusScheduleId")
                        .HasColumnType("uuid");

                    b.Property<int>("Column")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusScheduleId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6d30d3e-8c67-4b83-86d5-1f47f0a22d2b"),
                            BusScheduleId = new Guid("e5b270af-9491-4b8d-953e-126aa36820b7"),
                            Column = 1,
                            Row = 1,
                            SeatNumber = "A1",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9b8b9a8c-8234-4a1e-9e5e-ba0f41a36c8f"),
                            BusScheduleId = new Guid("e5b270af-9491-4b8d-953e-126aa36820b7"),
                            Column = 2,
                            Row = 1,
                            SeatNumber = "A2",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardingPointId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("BusScheduleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DroppingPointId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Fare")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardingPointId");

                    b.HasIndex("BusScheduleId");

                    b.HasIndex("DroppingPointId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("SeatId")
                        .IsUnique();

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaef5d47-7c32-48aa-9c0d-0acb03b6e2d9"),
                            BoardingPointId = new Guid("eab6b539-1981-460d-a0e1-7ee4a53b1299"),
                            BookingTime = new DateTime(2025, 10, 25, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            BusScheduleId = new Guid("e5b270af-9491-4b8d-953e-126aa36820b7"),
                            DroppingPointId = new Guid("bf14e6d2-ba55-4fbb-ac59-48a5f8a6407a"),
                            Fare = 500m,
                            PassengerId = new Guid("b1aa236b-9611-4e2c-8157-64a4be53c3ad"),
                            SeatId = new Guid("9b8b9a8c-8234-4a1e-9e5e-ba0f41a36c8f"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("59f72a9f-0561-4b9f-8e7b-965f899b9e90"),
                            BoardingPointId = new Guid("bf14e6d2-ba55-4fbb-ac59-48a5f8a6407a"),
                            BookingTime = new DateTime(2025, 10, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            BusScheduleId = new Guid("e5b270af-9491-4b8d-953e-126aa36820b7"),
                            DroppingPointId = new Guid("c318afac-ee1a-43ba-97f1-79acbd78d2a5"),
                            Fare = 300m,
                            PassengerId = new Guid("d31771d2-0c5e-4e1f-92f0-4d68c6e3123f"),
                            SeatId = new Guid("b6d30d3e-8c67-4b83-86d5-1f47f0a22d2b"),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.BusSchedule", b =>
                {
                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.Bus", "Bus")
                        .WithMany("Schedules")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.Route", "Route")
                        .WithMany("BusSchedules")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.RouteDroppingPoint", b =>
                {
                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.City", "City")
                        .WithMany("DroppingPoints")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.Route", "Route")
                        .WithMany("DroppingPoints")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("City");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Seat", b =>
                {
                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.BusSchedule", "BusSchedule")
                        .WithMany("Seats")
                        .HasForeignKey("BusScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusSchedule");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.RouteDroppingPoint", null)
                        .WithMany()
                        .HasForeignKey("BoardingPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.BusSchedule", "BusSchedule")
                        .WithMany("Tickets")
                        .HasForeignKey("BusScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.RouteDroppingPoint", null)
                        .WithMany()
                        .HasForeignKey("DroppingPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.Passenger", "Passenger")
                        .WithMany("Tickets")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.Seat", "Seat")
                        .WithOne("Ticket")
                        .HasForeignKey("Wafi.BusReservationSystem.Domain.Entities.Ticket", "SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusSchedule");

                    b.Navigation("Passenger");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Bus", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.BusSchedule", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.City", b =>
                {
                    b.Navigation("DroppingPoints");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Passenger", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Route", b =>
                {
                    b.Navigation("BusSchedules");

                    b.Navigation("DroppingPoints");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Seat", b =>
                {
                    b.Navigation("Ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
