// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wafi.BusReservationSystem.Infrastructure.Data;

#nullable disable

namespace Wafi.BusReservationSystem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WafiDbContext))]
    partial class WafiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Bus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0fadbf4c-f8cf-4937-86a2-0ca33feb33f9"),
                            BusName = "Hanif Volvo AC",
                            CompanyName = "Hanif Enterprise",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = new Guid("cea979fd-08fd-4b38-b14a-b2518b481112"),
                            BusName = "ENA Non AC",
                            CompanyName = "ENA Enterprise",
                            TotalSeats = 36
                        },
                        new
                        {
                            Id = new Guid("81630e00-df5d-4c49-a335-aaeb0e44a4d4"),
                            BusName = "Scania Business Class",
                            CompanyName = "Green Line Paribahan",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = new Guid("39b76299-f549-4fc6-99a0-a15a607cb510"),
                            BusName = "Hino non-AC",
                            CompanyName = "Hanif Enterprise",
                            TotalSeats = 34
                        });
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.BusSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("BusId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("JourneyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("RouteId");

                    b.ToTable("BusSchedules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("164dc434-d1c9-4220-88f0-407517f7434c"),
                            ArrivalTime = new TimeSpan(0, 8, 0, 0, 0),
                            BusId = new Guid("0fadbf4c-f8cf-4937-86a2-0ca33feb33f9"),
                            DepartureTime = new TimeSpan(0, 10, 0, 0, 0),
                            JourneyDate = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 700,
                            RouteId = new Guid("39b76299-f549-4fc6-99a0-a15a607cb510")
                        },
                        new
                        {
                            Id = new Guid("a83f3b24-cb63-4ec4-bc80-ef4eaaba047d"),
                            ArrivalTime = new TimeSpan(0, 19, 0, 0, 0),
                            BusId = new Guid("81630e00-df5d-4c49-a335-aaeb0e44a4d4"),
                            DepartureTime = new TimeSpan(0, 20, 0, 0, 0),
                            JourneyDate = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1200,
                            RouteId = new Guid("81630e00-df5d-4c49-a335-aaeb0e44a4d4")
                        });
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f91d9f76-694c-42d5-afca-69252dc86eff"),
                            Name = "Dhaka"
                        },
                        new
                        {
                            Id = new Guid("39b76299-f549-4fc6-99a0-a15a607cb510"),
                            Name = "Sirajgonj"
                        },
                        new
                        {
                            Id = new Guid("24a44820-cff8-4509-aa16-a1f4c5bb0bd5"),
                            Name = "Rajshahi"
                        },
                        new
                        {
                            Id = new Guid("4db86802-9aea-4e7e-801a-b05a2463be39"),
                            Name = "Khulna"
                        });
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Passenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39b76299-f549-4fc6-99a0-a15a607cb510"),
                            MobileNumber = "01976913524",
                            Name = "Sabbir Ahmed"
                        },
                        new
                        {
                            Id = new Guid("81630e00-df5d-4c49-a335-aaeb0e44a4d4"),
                            MobileNumber = "01776913524",
                            Name = "Hasan Tarik"
                        });
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromCityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToCityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromCityId");

                    b.HasIndex("ToCityId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39b76299-f549-4fc6-99a0-a15a607cb510"),
                            FromCityId = new Guid("f91d9f76-694c-42d5-afca-69252dc86eff"),
                            ToCityId = new Guid("24a44820-cff8-4509-aa16-a1f4c5bb0bd5")
                        },
                        new
                        {
                            Id = new Guid("81630e00-df5d-4c49-a335-aaeb0e44a4d4"),
                            FromCityId = new Guid("f91d9f76-694c-42d5-afca-69252dc86eff"),
                            ToCityId = new Guid("4db86802-9aea-4e7e-801a-b05a2463be39")
                        });
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.RouteDroppingPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("interval");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteDroppingPoints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("164dc434-d1c9-4220-88f0-407517f7434c"),
                            ArrivalTime = new TimeSpan(9, 2, 0, 0, 0),
                            CityId = new Guid("f91d9f76-694c-42d5-afca-69252dc86eff"),
                            DepartureTime = new TimeSpan(0, 8, 0, 0, 0),
                            Distance = 0.0,
                            Order = 1,
                            RouteId = new Guid("39b76299-f549-4fc6-99a0-a15a607cb510")
                        },
                        new
                        {
                            Id = new Guid("a83f3b24-cb63-4ec4-bc80-ef4eaaba047d"),
                            ArrivalTime = new TimeSpan(9, 16, 0, 0, 0),
                            CityId = new Guid("39b76299-f549-4fc6-99a0-a15a607cb510"),
                            DepartureTime = new TimeSpan(0, 8, 50, 0, 0),
                            Distance = 25.0,
                            Order = 2,
                            RouteId = new Guid("39b76299-f549-4fc6-99a0-a15a607cb510")
                        },
                        new
                        {
                            Id = new Guid("4db86802-9aea-4e7e-801a-b05a2463be39"),
                            ArrivalTime = new TimeSpan(10, 20, 0, 0, 0),
                            CityId = new Guid("24a44820-cff8-4509-aa16-a1f4c5bb0bd5"),
                            DepartureTime = new TimeSpan(0, 11, 0, 0, 0),
                            Distance = 50.0,
                            Order = 3,
                            RouteId = new Guid("39b76299-f549-4fc6-99a0-a15a607cb510")
                        });
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusScheduleId")
                        .HasColumnType("uuid");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BusScheduleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.BusSchedule", b =>
                {
                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Route", b =>
                {
                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.City", "FromCity")
                        .WithMany()
                        .HasForeignKey("FromCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.City", "ToCity")
                        .WithMany()
                        .HasForeignKey("ToCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromCity");

                    b.Navigation("ToCity");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.RouteDroppingPoint", b =>
                {
                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.Route", "Route")
                        .WithMany("Stops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Wafi.BusReservationSystem.Domain.Entities.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Wafi.BusReservationSystem.Domain.Entities.Route", b =>
                {
                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
